### ISSUE TITLE
domain() resolves to wrong domain

### ISSUE THREAD

**Issue by sampov2** [cmtt/publicsuffixlist#4]
Version 0.2.2 of psl.domain() resolves the hostname 'ogc.beta.agiv.be' incorrectly to 'ogc.beta.agiv.de'. The effective_tld_names.dat used by publicsuffixlist does not contain anything special for a "ogc", "beta" or "agiv".

```javascript
var PublicSuffixList = require('publicsuffixlist');
var psl = new PublicSuffixList();
psl.initializeSync();
psl.domain('agiv.be'); // => 'agiv.be' as expected
psl.domain('beta.agiv.be'); // => 'agiv.be' as expected
psl.domain('ogc.beta.agiv.be'); // => 'ogc.beta.agiv.be' !?
```

**Comment by cmtt** [comment]
Thank you for reporting this issue, it was corrected in 0.2.3
