### ISSUE TITLE
Uneeded dependencies downloaded during install.

### ISSUE THREAD

**Issue by jcpst** [cmtt/publicsuffixlist#8]
Because `gulp` `gulp-di` `gulp-istanbul` `gulp-jshint` `gulp-mocha` and `mocha` are all listed as `dependencies` rather than `devDependencies`, there are a ton of extra modules that are needlessly downloaded for people just using the module.

**suggestion:** Move the listed modules to `devDependencies`

**Comment by jcpst** [comment]
Looks like merging #7 would resolve this.

**Comment by cmtt** [comment]
Hello @jcpst, #7 has been merged.

Nevertheless, this resolves the issue solely partly. npm's default behaviour is to install dependencies as well as devDependencies as long as either the "--only=production" flag or the NODE_ENV=production environment variable are not set.

Therefore, a note to README.md to make use of one of these options has been added to the recent update.
