### ISSUE TITLE
Doesn't work with node 12

### ISSUE THREAD

**Issue by jribbens** [cmtt/publicsuffixlist#9]
publicsuffixlist doesn't work with node 12 - it fails 11 of its tests and produces completely wrong results, e.g.:
```
> psl.domain('example.org.uk')
'org.uk'
```

**Comment by cmtt** [comment]
Hello @jribbens, thank you for reporting this issue. I can confirm this issue, it is due to a non-default usage of `Array.prototype.sort` whose implementation has changed in V8 earlier this year.

A bugfix will be published within the next few hours.

**Comment by cmtt** [comment]
Version 0.3.0 has been released, addressing this issue.
